# Generated by Django 4.2.24 on 2025-09-27 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_doctor'),
        ('billing', '0002_alter_invoice_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpayment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.doctor'),
        ),
    ]
