# Generated by Django 4.2.24 on 2025-09-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_doctorpayment_doctor_alter_invoice_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Academy Dental Lab', max_length=120)),
                ('slogan', models.CharField(blank=True, default='', max_length=160)),
                ('logo_file', models.ImageField(blank=True, null=True, upload_to='lab/')),
                ('logo_static_path', models.CharField(blank=True, help_text='مثال: img/academy-logo.png (برای استفاده با {% static %})', max_length=255)),
                ('card_no', models.CharField(blank=True, max_length=64)),
                ('iban', models.CharField(blank=True, max_length=64)),
                ('account_name', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lab profile',
                'verbose_name_plural': 'Lab profile',
            },
        ),
    ]
