# Generated by Django 4.2.24 on 2025-10-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_labprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpayment',
            name='allocation_status',
            field=models.CharField(choices=[('unallocated', 'بدون تخصیص'), ('partial', 'بخشی تخصیص\u200cیافته'), ('allocated', 'کامل تخصیص\u200cیافته')], db_index=True, default='unallocated', max_length=20),
        ),
    ]
