# Generated by Django 4.2.24 on 2025-10-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_doctorpayment_allocation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('category', models.CharField(choices=[('materials', 'مواد اولیه'), ('labor', 'دستمزد'), ('rent', 'اجاره'), ('transport', 'حمل\u200cونقل'), ('overhead', 'سربار'), ('other', 'متفرقه')], max_length=64, verbose_name='دسته\u200cبندی')),
                ('product_type', models.CharField(blank=True, max_length=64, verbose_name='نوع محصول (اختیاری)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ')),
                ('vendor', models.CharField(blank=True, max_length=128, verbose_name='فروشنده / شخص')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'هزینه',
                'verbose_name_plural': 'هزینه\u200cها',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date'], name='billing_exp_date_31b117_idx'), models.Index(fields=['category'], name='billing_exp_categor_c99eaa_idx'), models.Index(fields=['product_type'], name='billing_exp_product_444af8_idx')],
            },
        ),
    ]
