# Generated by Django 4.2.24 on 2025-10-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='billing_exp_product_444af8_idx',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vendor',
        ),
        migrations.AddField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='expenses/'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('materials', 'مواد و متریال'), ('courier', 'پیک/حمل'), ('rent', 'اجاره/شارژ'), ('repairs', 'تعمیرات/نگهداری'), ('utilities', 'آب/برق/گاز/اینترنت'), ('salary', 'دستمزد/حق\u200cالزحمه'), ('misc', 'سایر')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
