# Generated by Django 4.2.24 on 2025-10-23 17:28

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_orderevent_stage_instance'),
        ('billing', '0007_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_unit', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار مصرف به\u200cازای یک واحد')),
                ('waste_factor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='ضریب تلفات (%)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BOM مصرف استاندارد',
                'verbose_name_plural': 'BOM مصرف استاندارد',
            },
        ),
        migrations.CreateModel(
            name='MaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='کد کالا (slug)')),
                ('name', models.CharField(max_length=160, verbose_name='نام متریال')),
                ('category', models.CharField(choices=[('porcelain', 'پرسلین'), ('metal', 'فلز/آلیاژ'), ('acrylic', 'آکریل/رزین'), ('abutment', 'اباتمنت/قطعات'), ('color', 'رنگ/استین'), ('other', 'سایر')], db_index=True, max_length=30)),
                ('uom', models.CharField(default='g', max_length=16, verbose_name='واحد (g|pcs|mL|...)')),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='حداقل موجودی')),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='عمر مفید (روز)')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کالای متریال',
                'verbose_name_plural': 'کالاهای متریال',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MaterialLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(blank=True, default='', max_length=80, verbose_name='کد لات/سری')),
                ('vendor', models.CharField(blank=True, default='', max_length=160, verbose_name='تأمین\u200cکننده')),
                ('purchase_date', models.DateField()),
                ('qty_in', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='تعداد/وزن خرید')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='قیمت واحد')),
                ('currency', models.CharField(blank=True, default='IRR', max_length=8)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=80)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='inventory/purchases/')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='billing.materialitem')),
            ],
            options={
                'verbose_name': 'لات خرید متریال',
                'verbose_name_plural': 'لات\u200cهای خرید متریال',
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'خرید'), ('issue', 'خروج به سفارش'), ('return_in', 'برگشت از سفارش'), ('waste', 'ضایعات/تلفات'), ('adjust_pos', 'اصلاح افزایشی'), ('adjust_neg', 'اصلاح کاهشی'), ('stocktake', 'شمارش/انبارگردانی')], db_index=True, max_length=20)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار (+/-)')),
                ('unit_cost_effective', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('happened_at', models.DateField(db_index=True)),
                ('product_code', models.CharField(blank=True, default='', max_length=60)),
                ('reason', models.CharField(blank=True, default='', max_length=160)),
                ('created_by', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='billing.materialitem')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='billing.materiallot')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.order')),
            ],
            options={
                'verbose_name': 'حرکت انبار',
                'verbose_name_plural': 'حرکت\u200cهای انبار',
                'ordering': ['-happened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_issued', models.DecimalField(decimal_places=3, max_digits=12)),
                ('comment', models.CharField(blank=True, default='', max_length=200)),
                ('happened_at', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='billing.materialitem')),
                ('linked_moves', models.ManyToManyField(blank=True, related_name='linked_issues', to='billing.stockmovement')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_issues', to='core.order')),
            ],
            options={
                'verbose_name': 'مصرف متریال (واقعی)',
                'verbose_name_plural': 'مصرف\u200cهای متریال (واقعی)',
            },
        ),
        migrations.AddIndex(
            model_name='materialitem',
            index=models.Index(fields=['code'], name='billing_mat_code_913ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='materialitem',
            index=models.Index(fields=['category', 'is_active'], name='billing_mat_categor_6fa78b_idx'),
        ),
        migrations.AddField(
            model_name='bomrecipe',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_usages', to='billing.materialitem'),
        ),
        migrations.AddField(
            model_name='bomrecipe',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='core.product'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'movement_type'], name='billing_sto_item_id_c0703c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['order'], name='billing_sto_order_i_d465cc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['happened_at'], name='billing_sto_happene_f5521b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockissue',
            index=models.Index(fields=['order'], name='billing_sto_order_i_31b9d8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockissue',
            index=models.Index(fields=['item'], name='billing_sto_item_id_ff1b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockissue',
            index=models.Index(fields=['happened_at'], name='billing_sto_happene_c80664_idx'),
        ),
        migrations.AddIndex(
            model_name='materiallot',
            index=models.Index(fields=['item'], name='billing_mat_item_id_3ac217_idx'),
        ),
        migrations.AddIndex(
            model_name='materiallot',
            index=models.Index(fields=['purchase_date'], name='billing_mat_purchas_022195_idx'),
        ),
        migrations.AddIndex(
            model_name='materiallot',
            index=models.Index(fields=['expire_date'], name='billing_mat_expire__675948_idx'),
        ),
        migrations.AddIndex(
            model_name='bomrecipe',
            index=models.Index(fields=['product', 'is_active'], name='billing_bom_product_fa9639_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bomrecipe',
            unique_together={('product', 'item')},
        ),
    ]
