# Generated by Django 4.2.24 on 2025-10-23 22:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_bomrecipe_materialitem_materiallot_stockmovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialitem',
            name='avg_unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='میانگین موزون فعلی'),
        ),
        migrations.AddField(
            model_name='materialitem',
            name='stock_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='موجودی فعلی'),
        ),
    ]
