# Generated by Django 4.2.24 on 2025-10-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_materialitem_avg_unit_cost_materialitem_stock_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialitem',
            name='item_type',
            field=models.CharField(choices=[('material', 'متریال'), ('tool', 'ابزار مصرفی')], default='material', max_length=16, verbose_name='نوع آیتم'),
        ),
        migrations.AddField(
            model_name='materialitem',
            name='pack_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد در هر باکس (اختیاری)'),
        ),
        migrations.AddField(
            model_name='materialitem',
            name='shade_enabled',
            field=models.BooleanField(default=False, verbose_name='دارای رنگ/Shade؟'),
        ),
        migrations.AddField(
            model_name='materiallot',
            name='end_use_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ اتمام مصرف'),
        ),
        migrations.AddField(
            model_name='materiallot',
            name='shade_code',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='رنگ/Shade (در صورت نیاز)'),
        ),
        migrations.AddField(
            model_name='materiallot',
            name='start_use_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ آغاز مصرف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'اجاره/شارژ'), ('utilities', 'قبض'), ('courier', 'پیک'), ('transport', 'حمل و نقل'), ('home', 'مخارج جاری منزل'), ('installment', 'قسط'), ('petty_cash', 'تنخواه لابراتوار'), ('misc', 'سایر'), ('materials', 'مواد و متریال'), ('repairs', 'تعمیرات/نگهداری'), ('salary', 'دستمزد/حق\u200cالزحمه')], db_index=True, max_length=24),
        ),
    ]
