# Generated by Django 4.2.24 on 2025-10-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_materialitem_item_type_materialitem_pack_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialitem',
            name='uom',
            field=models.CharField(choices=[('g', 'گرم'), ('kg', 'کیلوگرم'), ('ml', 'میلی\u200cلیتر'), ('l', 'لیتر'), ('pcs', 'عدد'), ('box', 'باکس')], default='g', max_length=16, verbose_name='واحد پایه (g|kg|ml|l|pcs|box)'),
        ),
    ]
