# Generated by Django 4.2.24 on 2025-10-27 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_equipment_repair_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_key', models.CharField(db_index=True, max_length=50, verbose_name='کلید مشترک مرحله (stage_key)')),
                ('shade_sensitive', models.BooleanField(default=False, verbose_name='وابسته به رنگ/Shade؟')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_defaults', to='billing.materialitem', verbose_name='متریال')),
            ],
            options={
                'verbose_name': 'پیش\u200cفرض متریالِ مرحله',
                'verbose_name_plural': 'پیش\u200cفرض\u200cهای متریالِ مرحله',
                'ordering': ['stage_key', 'material'],
                'indexes': [models.Index(fields=['stage_key', 'material'], name='billing_sta_stage_k_cd11a5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='stagedefault',
            constraint=models.UniqueConstraint(fields=('stage_key', 'material'), name='uniq_stage_default_stage_material'),
        ),
    ]
