# Generated by Django 4.2.24 on 2025-10-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_stagedefault_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallot',
            name='allocated',
            field=models.BooleanField(default=False, verbose_name='لات تخصیص یافته؟'),
        ),
        migrations.AddField(
            model_name='materiallot',
            name='allocated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تخصیص'),
        ),
        migrations.AddIndex(
            model_name='materiallot',
            index=models.Index(fields=['allocated'], name='billing_mat_allocat_7c36a7_idx'),
        ),
    ]
