# Generated by Django 4.2.24 on 2025-10-30 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_stagetemplate_stage_key'),
        ('billing', '0014_materiallot_allocated_materiallot_allocated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualStockIssue',
            fields=[
            ],
            options={
                'verbose_name': 'مصرف دستی متریال (کارتکس)',
                'verbose_name_plural': 'مصرف\u200cهای دستی متریال (کارتکس)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.stockmovement',),
        ),
        migrations.CreateModel(
            name='DigitalLabCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, default='', max_length=160, verbose_name='نام لابراتوار دیجیتال / فروشنده')),
                ('service', models.CharField(choices=[('scan', 'اسکن'), ('design', 'طراحی دیجیتال'), ('print', 'پرینت سه\u200cبعدی'), ('milling', 'میلینگ'), ('package', 'پکج کامل'), ('other', 'سایر خدمات')], default='other', max_length=40, verbose_name='نوع خدمت')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ (تومان)')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='digital_lab/', verbose_name='پیوست فاکتور/رسید')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_charges', to='core.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'هزینه لابراتوار دیجیتال',
                'verbose_name_plural': 'هزینه\u200cهای لابراتوار دیجیتال',
                'ordering': ['-payment_date', '-id'],
                'indexes': [models.Index(fields=['order'], name='billing_dig_order_i_dab4a9_idx'), models.Index(fields=['service'], name='billing_dig_service_09c31a_idx'), models.Index(fields=['payment_date'], name='billing_dig_payment_74e826_idx')],
            },
        ),
    ]
