# Generated by Django 4.2.24 on 2025-10-30 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_digitallabtransfer_attempt_no_and_more'),
        ('billing', '0015_manualstockissue_digitallabcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitallabcharge',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='core.digitallabtransfer', verbose_name='ارسال مرتبط (نوبت)'),
        ),
        migrations.AddIndex(
            model_name='digitallabcharge',
            index=models.Index(fields=['transfer'], name='billing_dig_transfe_bdcddf_idx'),
        ),
    ]
