# Generated by Django 4.2.24 on 2025-10-31 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_digitallabcharge_transfer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigitalLabCharge',
        ),
    ]
