# Generated by Django 4.2.24 on 2025-09-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت کل (تومان)'),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_count',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد واحد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('crown_pfm', 'Crown (P.F.M)'), ('crown_zirconia', 'Crown (Zirconia)'), ('implant_pfm', 'Implant (P.F.M)'), ('implant_zirconia', 'Implant (Zirconia)'), ('post_core_np', 'Post & Core (N.P)'), ('post_core_npg', 'Post & Core (N.P.G)'), ('laminat_press', 'Laminat (Press)'), ('laminat_zirconia', 'Laminat (Zirconia)'), ('jig_special_trey', 'Jig & Special Trey'), ('full_wax_up', 'Full Wax up'), ('denture', 'Denture')], max_length=30, null=True, verbose_name='نوع کار'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت به ازای هر واحد (تومان)'),
        ),
    ]
