# Generated by Django 4.2.24 on 2025-09-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_total_price_order_unit_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره سریال'),
        ),
    ]
