# Generated by Django 4.2.24 on 2025-09-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='نام بیمار', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('crown_pfm', 'Crown(P.F.M)'), ('crown_zirconia', 'Crown(Zirconia)'), ('implant_pfm', 'Implant(P.F.M)'), ('implant_zirconia', 'Implant(Zirconia)'), ('post_core_np', 'Post & Core(N.P)'), ('post_core_npg', 'Post & Core(N.P.G)'), ('laminat_press', 'Laminat(Press)'), ('laminat_zirconia', 'Laminat(Zirconia)'), ('jig_special', 'Jig & Special Trey'), ('full_waxup', 'Full Wax up'), ('denture', 'Denture')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
