# Generated by Django 4.2.24 on 2025-09-19 12:10

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_order_total_price_remove_patient_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ پرداخت')),
                ('method', models.CharField(blank=True, max_length=50, null=True, verbose_name='روش پرداخت')),
                ('date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ثبت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
