# Generated by Django 4.2.24 on 2025-09-22 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_accounting_delete_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounting',
            options={'verbose_name': 'گزارش مالی', 'verbose_name_plural': 'گزارش مالی'},
        ),
    ]
