# Generated by Django 4.2.24 on 2025-09-26 16:07

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_accounting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ارسال (واقعی)'),
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'ثبت سفارش'), ('received_in_lab', 'دریافت در لابراتوار'), ('in_progress', 'در حال انجام'), ('sent_to_clinic', 'ارسال به مطب'), ('returned_from_clinic', 'بازگشت از مطب'), ('sent_to_digital_lab', 'ارسال به لابراتوار دیجیتال'), ('received_from_digital_lab', 'دریافت از لابراتوار دیجیتال'), ('adjustment', 'اصلاح/ری\u200cورک'), ('glaze', 'گلیز نهایی'), ('final_shipment', 'ارسال نهایی'), ('delivered', 'تحویل قطعی'), ('note', 'یادداشت'), ('frame_try_in', 'امتحان فریم'), ('porcelain_try_in', 'امتحان پرسلن'), ('components_received', 'دریافت قطعات از مطب'), ('dural_try_in', 'امتحان دورالی'), ('wax_rim_record_bite', 'Wax rim & Record bite')], max_length=50)),
                ('happened_at', django_jalali.db.models.jDateField(verbose_name='تاریخ وقوع')),
                ('direction', models.CharField(blank=True, choices=[('lab→clinic', 'لابراتوار → مطب'), ('clinic→lab', 'مطب → لابراتوار'), ('lab→digital', 'لابراتوار → دیجیتال'), ('digital→lab', 'دیجیتال → لابراتوار'), ('internal', 'داخلی')], max_length=20)),
                ('stage', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='order_events/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.order')),
            ],
            options={
                'ordering': ['happened_at', 'id'],
            },
        ),
    ]
