# Generated by Django 4.2.24 on 2025-09-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_shipped_date_orderevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام دکتر/مطب')),
                ('clinic', models.CharField(blank=True, max_length=150, verbose_name='کلینیک/آدرس کوتاه')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='کد داخلی/ارجاع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دکتر',
                'verbose_name_plural': 'دکترها',
                'ordering': ['name'],
            },
        ),
    ]
