# Generated by Django 4.2.24 on 2025-10-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(blank=True, default='', max_length=200, verbose_name='نام لابراتوار')),
                ('address', models.TextField(blank=True, default='', verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='تلفن')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=50, verbose_name='واتس\u200cاپ')),
                ('currency', models.CharField(blank=True, default='تومان', max_length=20, verbose_name='واحد پول')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نرخ مالیات (%)')),
                ('default_due_days', models.PositiveSmallIntegerField(default=7, verbose_name='مهلت پیش\u200cفرض (روز)')),
                ('jalali_enabled', models.BooleanField(default=True, verbose_name='تقویم جلالی فعال باشد؟')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='لوگو (اختیاری)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات لابراتوار',
                'verbose_name_plural': 'تنظیمات لابراتوار',
            },
        ),
    ]
