# Generated by Django 4.2.24 on 2025-10-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_labsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='teeth_fdi',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='کدهای FDI'),
        ),
    ]
