# Generated by Django 4.2.24 on 2025-10-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_teeth_fdi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='کد محصول (لاتین/slug)')),
                ('name', models.CharField(max_length=120, verbose_name='نام محصول')),
                ('category', models.CharField(blank=True, default='', max_length=80, verbose_name='دسته\u200cبندی')),
                ('default_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت واحد پیش\u200cفرض (اختیاری)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('notes', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['name', 'code'],
            },
        ),
    ]
