# Generated by Django 4.2.24 on 2025-10-10 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(verbose_name='کلید مرحله (slug لاتین)')),
                ('label', models.CharField(max_length=120, verbose_name='عنوان مرحله برای نمایش')),
                ('order_index', models.PositiveSmallIntegerField(verbose_name='ترتیب مرحله')),
                ('default_duration_days', models.PositiveSmallIntegerField(default=1, verbose_name='مدت پیشنهادی (روز)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('notes', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مرحلهٔ محصول',
                'verbose_name_plural': 'مراحل محصولات',
                'ordering': ['product', 'order_index'],
            },
        ),
        migrations.AddConstraint(
            model_name='stagetemplate',
            constraint=models.UniqueConstraint(fields=('product', 'key'), name='uniq_stage_key_per_product'),
        ),
        migrations.AddConstraint(
            model_name='stagetemplate',
            constraint=models.UniqueConstraint(fields=('product', 'order_index'), name='uniq_stage_order_per_product'),
        ),
    ]
