# Generated by Django 4.2.24 on 2025-10-10 21:22

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_stagetemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('planned_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('started_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('done_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'در صف'), ('in_progress', 'در حال انجام'), ('done', 'انجام شد'), ('blocked', 'متوقف')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.order')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='core.stagetemplate')),
            ],
            options={
                'verbose_name': 'مرحلهٔ سفارش',
                'verbose_name_plural': 'مراحل سفارش',
                'ordering': ['order', 'order_index', 'id'],
                'unique_together': {('order', 'key')},
            },
        ),
    ]
