# Generated by Django 4.2.24 on 2025-10-14 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_stageinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderevent',
            name='stage_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.stageinstance', verbose_name='مرحله مرتبط (اختیاری)'),
        ),
    ]
