# Generated by Django 4.2.24 on 2025-10-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_orderevent_stage_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetemplate',
            name='stage_key',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='کلید مشترک مرحله (برای گروه\u200cبندی مراحل مشابه بین محصولات)'),
        ),
    ]
