# Generated by Django 4.2.24 on 2025-10-30 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_stagetemplate_stage_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalLabTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=160, verbose_name='نام لابراتوار دیجیتال')),
                ('stage_name', models.CharField(max_length=160, verbose_name='مرحله مربوطه (مثلاً فریم، میلینگ، طراحی)')),
                ('sent_date', models.DateField(verbose_name='تاریخ ارسال')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='تاریخ دریافت')),
                ('status', models.CharField(choices=[('sent', 'ارسال\u200cشده'), ('received', 'تحویل\u200cگرفته\u200cشده'), ('cancelled', 'لغو شده')], default='sent', max_length=20, verbose_name='وضعیت')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='هزینه (تومان)')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_lab_transfers', to='core.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'ارسال به لاب دیجیتال',
                'verbose_name_plural': 'ارسال\u200cها به لاب دیجیتال',
                'ordering': ['-sent_date', '-id'],
                'indexes': [models.Index(fields=['order'], name='core_digita_order_i_6cc42b_idx'), models.Index(fields=['sent_date'], name='core_digita_sent_da_603b3c_idx'), models.Index(fields=['status'], name='core_digita_status_7f404a_idx')],
            },
        ),
    ]
