# Generated by Django 4.2.24 on 2025-10-30 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_digitallabtransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitallabtransfer',
            name='attempt_no',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='نوبت (Attempt #)'),
        ),
        migrations.AddField(
            model_name='digitallabtransfer',
            name='charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ این نوبت (تومان)'),
        ),
        migrations.AddField(
            model_name='digitallabtransfer',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='اعتبار/برگشت این نوبت (تومان)'),
        ),
        migrations.AddField(
            model_name='digitallabtransfer',
            name='is_redo',
            field=models.BooleanField(default=False, verbose_name='تکرار/ری\u200cورک؟'),
        ),
        migrations.AddField(
            model_name='digitallabtransfer',
            name='redo_reason',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='علت تکرار'),
        ),
        migrations.AddField(
            model_name='digitallabtransfer',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redo_children', to='core.digitallabtransfer', verbose_name='مرتبط با نوبت قبلی'),
        ),
        migrations.AlterField(
            model_name='digitallabtransfer',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='(قدیمی) هزینه (تومان)'),
        ),
        migrations.AddIndex(
            model_name='digitallabtransfer',
            index=models.Index(fields=['attempt_no'], name='core_digita_attempt_247fb2_idx'),
        ),
    ]
