# Generated by Django 4.2.24 on 2025-10-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_digitallabtransfer_attempt_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitallabtransfer',
            name='shade_code',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='رنگ (Shade)'),
        ),
        migrations.AddField(
            model_name='digitallabtransfer',
            name='stage_key',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='کلید مرحله (اختیاری)'),
        ),
    ]
