# Generated by Django 4.2.24 on 2025-11-09 22:21

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_digitallabtransfer_shade_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام تکنسین')),
                ('role', models.CharField(blank=True, default='', max_length=80, verbose_name='نقش/تخصص')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تکنسین',
                'verbose_name_plural': 'تکنسین\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stagetemplate',
            name='base_wage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='دستمزد پایه هر واحد (تومان)'),
        ),
        migrations.CreateModel(
            name='StageWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('finished_at', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, verbose_name='تعداد واحد')),
                ('unit_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='نرخ هر واحد (تومان)')),
                ('total_wage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='مبلغ کل (تومان)')),
                ('status', models.CharField(choices=[('in_progress', 'در حال انجام'), ('done', 'انجام شد'), ('cancelled', 'لغو شده')], default='done', max_length=20, verbose_name='وضعیت')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_worklogs', to='core.order', verbose_name='سفارش')),
                ('stage_inst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to='core.stageinstance', verbose_name='مرحلهٔ سفارش (اختیاری)')),
                ('stage_tpl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to='core.stagetemplate', verbose_name='مرحلهٔ مرجع (Template)')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to='core.technician', verbose_name='تکنسین')),
            ],
            options={
                'verbose_name': 'لاگ مرحله (دستمزد)',
                'verbose_name_plural': 'لاگ\u200cهای مرحله (دستمزد)',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['order'], name='core_stagew_order_i_6c4b64_idx'), models.Index(fields=['stage_tpl'], name='core_stagew_stage_t_828a51_idx'), models.Index(fields=['technician'], name='core_stagew_technic_43736f_idx')],
            },
        ),
        migrations.CreateModel(
            name='StageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='نرخ هر واحد (تومان)')),
                ('effective_from', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع اعتبار')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.stagetemplate', verbose_name='مرحله')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_rates', to='core.technician', verbose_name='تکنسین')),
            ],
            options={
                'verbose_name': 'نرخ مرحله (تکنسین)',
                'verbose_name_plural': 'نرخ\u200cهای مرحله (تکنسین)',
                'ordering': ['stage', 'technician', '-effective_from'],
                'indexes': [models.Index(fields=['stage', 'technician', 'effective_from'], name='core_stager_stage_i_35d53a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='stagerate',
            constraint=models.UniqueConstraint(fields=('stage', 'technician', 'effective_from'), name='uniq_stage_rate_per_date'),
        ),
    ]
