# Generated by Django 4.2.24 on 2025-11-13 14:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_technician_stagetemplate_base_wage_stageworklog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageworklog',
            name='is_settled',
            field=models.BooleanField(default=False, verbose_name='تسویه\u200cشده؟'),
        ),
        migrations.AddField(
            model_name='stageworklog',
            name='settled_at_j',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تسویه'),
        ),
        migrations.CreateModel(
            name='WagePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start_j', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ شروع بازه')),
                ('period_end_j', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان بازه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('confirmed', 'تأییدشده'), ('paid', 'پرداخت\u200cشده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('gross_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='جمع ناخالص دستمزد')),
                ('deductions_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='جمع کسورات')),
                ('bonus_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='جمع پاداش')),
                ('net_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='خالص قابل پرداخت')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='توضیحات')),
                ('payment_ref', models.CharField(blank=True, default='', max_length=120, verbose_name='مرجع/شماره سند پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wage_payouts', to='core.technician', verbose_name='تکنسین')),
            ],
            options={
                'verbose_name': 'تسویه دستمزد',
                'verbose_name_plural': 'تسویه\u200cهای دستمزد',
                'ordering': ['-period_end_j', '-id'],
            },
        ),
        migrations.AddField(
            model_name='stageworklog',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to='core.wagepayout', verbose_name='تسویه مرتبط'),
        ),
    ]
