# Generated by Django 4.2.24 on 2025-12-17 22:21

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_stageworklog_is_settled_stageworklog_settled_at_j_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="کلید مرحله"
                    ),
                ),
                (
                    "stage_label",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="عنوان مرحله"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("stage_change", "تغییر مرحله"),
                            ("clinic_send", "ارسال به مطب"),
                            ("clinic_receive", "دریافت از مطب"),
                            ("digital_send", "ارسال به لاب دیجیتال"),
                            ("digital_receive", "دریافت از لاب دیجیتال"),
                            ("note", "یادداشت"),
                        ],
                        max_length=30,
                        verbose_name="نوع رویداد",
                    ),
                ),
                (
                    "responsible",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="مسئول/اپراتور"
                    ),
                ),
                (
                    "started_at",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ شروع/وقوع"
                    ),
                ),
                (
                    "finished_at",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ پایان"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="جزئیات تکمیلی"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_events",
                        to="core.order",
                        verbose_name="سفارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "رویداد تولید",
                "verbose_name_plural": "رویدادهای تولید",
                "ordering": ["-started_at", "-id"],
            },
        ),
    ]
